move epelbeta to epel7

diff --git a/scripts/buildepelbeta b/scripts/buildepelbeta
--- a/scripts/buildepelbeta
+++ b/scripts/buildepelbeta
@@ -7,8 +7,8 @@
 
 DATE=$1
 RSYNC_OPTS="-rlptDHhv --delay-updates"
-DESTPATH="/pub/epel/beta/6/"
-MOCKCONFIG=rhel-compose-i386
+DESTPATH="/pub/epel/beta/7/"
+MOCKCONFIG=rhel-compose-x86_64
 
 
 [ -z "$DATE" ] && {
@@ -30,27 +30,27 @@ echo "start" | fedmsg-logger \
 pushd $TMPDIR
 git clone git://git.fedorahosted.org/comps.git && {
 	pushd comps
-	make comps-el6.xml
-	cp comps-el6.xml /mnt/koji/mash/epel-$DATE/logs/
+	make comps-epel7.xml
+	cp comps-epel7.xml /mnt/koji/mash/epel-$DATE/logs/
 	popd
 }
 popd
 
-[ -f /mnt/koji/mash/epel-$DATE/logs/comps-el6.xml ] || exit 1
+[ -f /mnt/koji/mash/epel-$DATE/logs/comps-epel7.xml ] || exit 1
 
 mock -r $MOCKCONFIG --uniqueext=$DATE --init
 mock -r $MOCKCONFIG --uniqueext=$DATE --no-clean --install koji yum createrepo cvs make intltool findutils mash yum-utils rsync repoview
 # Copy in the hosts file so that we get the right address for koji
 mock -r $MOCKCONFIG --uniqueext=$DATE --copyin /etc/hosts /etc/hosts >/dev/null 2>&1 # this reports to fail, but actually works
-mock -r $MOCKCONFIG --uniqueext=$DATE --copyin /etc/mash/el6-epel.mash /etc/mash/el6-epel.mash > /dev/null 2>&1 # this reports to fail, but actually works
-mock -r $MOCKCONFIG --uniqueext=$DATE --copyin /usr/share/mash/spam-o-matic-el6 /usr/share/mash/spam-o-matic-el6 > /dev/null 2>&1 # this reports to fail, but actually works
+mock -r $MOCKCONFIG --uniqueext=$DATE --copyin /etc/mash/epel7.mash /etc/mash/epel7.mash > /dev/null 2>&1 # this reports to fail, but actually works
+mock -r $MOCKCONFIG --uniqueext=$DATE --copyin /usr/share/mash/spam-o-matic-epel7 /usr/share/mash/spam-o-matic-epel7 > /dev/null 2>&1 # this reports to fail, but actually works
 # Drop privs here so that we run as the masher UID
-mock -r $MOCKCONFIG --uniqueext=$DATE --unpriv --chroot "mash -o /mnt/koji/mash/epel-$DATE --compsfile /mnt/koji/mash/epel-$DATE/logs/comps-el6.xml el6-epel > /mnt/koji/mash/epel-$DATE/logs/mash.log 2>&1" || exit 1
+mock -r $MOCKCONFIG --uniqueext=$DATE --unpriv --chroot "mash -o /mnt/koji/mash/epel-$DATE --compsfile /mnt/koji/mash/epel-$DATE/logs/comps-epel7.xml epel7 > /mnt/koji/mash/epel-$DATE/logs/mash.log 2>&1" || exit 1
 
 mock -r $MOCKCONFIG --uniqueext=$DATE --chroot "rm -f /var/lib/rpm/__db*"
-mock -r $MOCKCONFIG --uniqueext=$DATE --unpriv --chroot "/usr/bin/repodiff -q --new=file:///mnt/koji/mash/epel-$DATE/el6-epel/SRPMS --old=file:///pub/epel/beta/6/SRPMS > /mnt/koji/mash/epel-$DATE/logs/repodiff"
+mock -r $MOCKCONFIG --uniqueext=$DATE --unpriv --chroot "/usr/bin/repodiff -q --new=file:///mnt/koji/mash/epel-$DATE/epel7/SRPMS --old=file:///pub/epel/beta/6/SRPMS > /mnt/koji/mash/epel-$DATE/logs/repodiff"
 
-mock -r $MOCKCONFIG --uniqueext=$DATE --unpriv --chroot "/usr/share/mash/spam-o-matic-el6 --treename=epel-6 /mnt/koji/mash/epel-$DATE/el6-epel/ >/mnt/koji/mash/epel-$DATE/logs/depcheck" &
+mock -r $MOCKCONFIG --uniqueext=$DATE --unpriv --chroot "/usr/share/mash/spam-o-matic-epel7 --treename=epel-6 /mnt/koji/mash/epel-$DATE/epel7/ >/mnt/koji/mash/epel-$DATE/logs/depcheck" &
 
 
 wait
@@ -66,10 +66,10 @@ echo "done" | fedmsg-logger \
 
 cd /tmp
 # data
-sudo -u ftpsync /usr/bin/rsync $RSYNC_OPTS --exclude repodata/ /mnt/koji/mash/epel-$DATE/el6-epel/ $DESTPATH
+sudo -u ftpsync /usr/bin/rsync $RSYNC_OPTS --exclude repodata/ /mnt/koji/mash/epel-$DATE/epel7/ $DESTPATH
 # repodata & cleanup
-sudo -u ftpsync /usr/bin/rsync $RSYNC_OPTS --delete --delete-after /mnt/koji/mash/epel-$DATE/el6-epel/ $DESTPATH
+sudo -u ftpsync /usr/bin/rsync $RSYNC_OPTS --delete --delete-after /mnt/koji/mash/epel-$DATE/epel7/ $DESTPATH
 if [ "$?" = "0" ]; then
-    cat /mnt/koji/mash/epel-$DATE/logs/start /mnt/koji/mash/epel-$DATE/logs/depcheck /mnt/koji/mash/epel-$DATE/logs/repodiff | mutt -e 'set from="EPEL Beta Report <epel@fedoraproject.org>"' -e 'set envelope_from=yes' -s 'epel beta report: '$DATE' changes' epel-devel-list@redhat.com
+    cat /mnt/koji/mash/epel-$DATE/logs/start /mnt/koji/mash/epel-$DATE/logs/depcheck /mnt/koji/mash/epel-$DATE/logs/repodiff | mutt -e 'set from="EPEL Beta Report <epel@fedoraproject.org>"' -e 'set envelope_from=yes' -s 'epel beta report: '$DATE' changes' epel-devel@lists.fedoraproject.org
 fi
 exit 0
